// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPDSIds
{
        public const string leaderboard_total_distance_traveled = "CgkIkJmRooATEAIQBw"; // <GPGSID>
        public const string leaderboard_max_distance_achieved = "CgkIkJmRooATEAIQAQ"; // <GPGSID>
        public const string leaderboard_no_of_upgrade_purchases = "CgkIkJmRooATEAIQCw"; // <GPGSID>
        public const string leaderboard_total_obstacles_destroyed = "CgkIkJmRooATEAIQDA"; // <GPGSID>
        public const string leaderboard_total_consumables_used = "CgkIkJmRooATEAIQEA"; // <GPGSID>
        public const string leaderboard_powerups_picked_up_in_single_run = "CgkIkJmRooATEAIQEg"; // <GPGSID>
        public const string leaderboard_max_coins_collected_in_single_run = "CgkIkJmRooATEAIQCQ"; // <GPGSID>
        public const string leaderboard_total_coins_collected = "CgkIkJmRooATEAIQCA"; // <GPGSID>
        public const string leaderboard_no_of_games_finished = "CgkIkJmRooATEAIQCg"; // <GPGSID>
        public const string leaderboard_total_lifepoints_lost = "CgkIkJmRooATEAIQEw"; // <GPGSID>
        public const string leaderboard_total_powerups_picked_up = "CgkIkJmRooATEAIQDw"; // <GPGSID>
        public const string leaderboard_obstacles_destroyed_in_single_run = "CgkIkJmRooATEAIQDQ"; // <GPGSID>

}

